- hosts: all
  become: True
  tasks:
    - name: Install packages
      apt:
        name: "nginx"
        state: "present"
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html # We have define a html page 
        dest: /var/www/html/
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Ensure Python 'six' module is installed
      pip:
        name: six
        executable: pip3
